name: Publish nuget package
 
on: [push]
 
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # SETUP DOTNET
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      # RESTORE NUGET PACKAGES
      - name: nuget setup and pack
        uses: NuGet/setup-nuget@v1.0.2
      - run: nuget pack source\PlottingControls.Framework\PlottingControls.Framework.nuspec
