name: Publish nuget package
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-tooldotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test
    - name: Pack with dotnet
      run: dotnet pack source/PlottingControls.Framework/PlottingControls.Framework.csproj --output nuget-packages --configuration Release
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY }} --source https://api.nuget.org/v3/index.json

# This is a basic workflow to help you get started with Actions
